require("dotenv").config();

import { ObjectId } from "mongodb";
import { connectDatabase } from "../src/database";
import { Listing, ListingType, User } from "../src/lib/types";

const listings: Listing[] = [
  {
    _id: new ObjectId("5d378db94e84753160e08b30"),
    title: "Spacious Room in East Village Architect’s Home",
    description:
      "Less than 1 mile from Town & Country Mall, Publix, Theatres, Restaurants. Within 10-15 minutes of Miami's best shopping Malls, Dadeland, Dolphin Mall, International mall, Sunset Place. Easy access to bus transportation and metrorail to anywhere in Miami.",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1608982220/peace-village/roger-starnes-sr-K-miZwWWLwE-unsplash_zuncta.jpg",
    host: "5d378db94e84753160e08b57",
    type: ListingType.Apartment,
    address: "Miami, Florida, United States",
    country: "United States",
    admin: "Florida",
    city: "Miami",
    bookings: [],
    bookingsIndex: {},
    price: 14320,
    numOfGuests: 4,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b31"),
    title: "Newly renovated basement bedroom with full bed",
    description:
      "Newly renovated bedroom in basement. Bathroom and kitchen are shared. Kitchen is equipped with pans, dishes, cups, silverware, kettle, etc! Soft water system throughout the house. ",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1608982220/peace-village/colton-sturgeon-0GI--3Pik8k-unsplash_itch1b.jpg",
    host: "5d378db94e84753160e08b55",
    type: ListingType.Apartment,
    address: "McCowan Rd and McNicoll Ave.",
    country: "Canada",
    admin: "Ontario",
    city: "Toronto",
    bookings: [],
    bookingsIndex: {},
    price: 30934,
    numOfGuests: 3,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b32"),
    title: "Restored Bungalow of Rockaway Beach",
    description:
      "we have limited our listing to (2) two guests but exceptions will be made to families with up to two children. We are taking all necessary precautions to provide a safe environment but please follow CDC guidelines at all times.",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1608982220/peace-village/randy-fath-jkPdp_bbPsE-unsplash_qlgjqr.jpg",
    host: "5d378db94e84753160e08b57",
    type: ListingType.House,
    address: "Queens, New York, United States",
    country: "United States",
    admin: "Queens",
    city: "New York",
    bookings: [],
    bookingsIndex: {},
    price: 30342,
    numOfGuests: 2,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b33"),
    title: "Luxury condo suite located in the heart of downtown Toronto",
    description:
      "Luxury condo suite located in the heart of the city with building pool/gym/sauna available 24/7. Buses, subway, and all other amenities are available close by. Booking comes with 1 available parking spot in building underground.",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1608982220/peace-village/benjamin-rascoe--UrDKR3QCog-unsplash_dhbjiy.jpg",
    host: "5d378db94e84753160e08b59",
    type: ListingType.Apartment,
    address: "9531 Prince Road, Toronto, ON, CA",
    country: "Canada",
    admin: "Ontario",
    city: "Toronto",
    bookings: [],
    bookingsIndex: {},
    price: 43209,
    numOfGuests: 4,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b34"),
    title: "Cozy 2 bedroom house located within the suburbs",
    description:
      "Cozy 2 bedroom house, located roughly 1 hour from the downtown hub. Close to all transporation systems such as the local bus terminal and subway.",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1608982220/peace-village/tony-long--BaHIsnHEAs-unsplash_bdymgv.jpg",
    host: "5d378db94e84753160e08b57",
    type: ListingType.House,
    address: "43 Tallwood Drive, Toronto, ON, CA",
    country: "Canada",
    admin: "Ontario",
    city: "Toronto",
    bookings: [],
    bookingsIndex: {},
    price: 32230,
    numOfGuests: 3,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b35"),
    title: "One bedroom suite at Arverne by the sea",
    description:
      "The property is a two level house with a walk-out ground floor completely separated from the main and upper floors. The lower ground floor has a full one bedroom apartment with windows that brings in natural light which is complemented with LED and florescence lighting to create a warm, cozy and bright atmosphere",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1608982220/peace-village/benjamin-rascoe-1nao7-vs7m4-unsplash_kgnxz2.jpg",
    host: "5d378db94e84753160e08b57",
    type: ListingType.House,
    address: "09 Morris Ave, Toronto, ON, CA",
    country: "Canada",
    admin: "Ontario",
    city: "Toronto",
    bookings: [],
    bookingsIndex: {},
    price: 50980,
    numOfGuests: 2,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b36"),
    title: "Picturesque 2 Story House - great location",
    description:
      "Beautiful and picturesque 2 story house located only minutes away from the center of Midtown Toronto. Street level parking available at all times. With four beds and three baths, house accomodates up to 6 guests comfortably.",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1608982221/peace-village/roger-starnes-sr-6MozY2aGLhI-unsplash_w08ps4.jpg",
    host: "5d378db94e84753160e08b57",
    type: ListingType.House,
    address: "12 Morris Ave, Toronto, ON, CA",
    country: "Canada",
    admin: "Ontario",
    city: "Toronto",
    bookings: [],
    bookingsIndex: {},
    price: 21877,
    numOfGuests: 1,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b37"),
    title: "Petite Gem in the Heart of Philadelphia",
    description:
      "Located in the prestigious Society Hill neighborhood, this snug little bedroom, in a 3-bedroom townhouse, is perfectly situated on a quiet, tree-lined street. This petite room overlooks a backyard and is fully furnished.",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1608982221/peace-village/joshua-gobin-ncDOmd9R4nE-unsplash_cyij9o.jpg",
    host: "5d378db94e84753160e08b56",
    type: ListingType.Apartment,
    address: "2275  Rosemont Avenue, Philadelphia, United States",
    country: "United States",
    admin: "Pennsylvania",
    city: "Philadelphia",
    bookings: [],
    bookingsIndex: {},
    price: 49821,
    numOfGuests: 4,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b38"),
    title: "Budget room #2 Center City South/Free Parking",
    description:
      "I welcome you no matter what your ethnic, religion, or sexual orientation, background. I believe in diversity.The room is located in a private 3 bedroom modern town home, that is 11 years old. The room is cozy and comfortable.",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1608982221/peace-village/vlad-gorshkov-dJkEY7hZKTM-unsplash_klmd6i.jpg",
    host: "5d378db94e84753160e08b56",
    type: ListingType.Apartment,
    address: "512  Winifred Way, Dubai, United Arab Emirates",
    country: "United Arab Emirates",
    admin: "Dubai",
    city: "Dubai",
    bookings: [],
    bookingsIndex: {},
    price: 22232,
    numOfGuests: 3,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b39"),
    title: "Monarch | Luxury Apartment in the Heart of Old City Philadelphia",
    description:
      "Brought to you by Monarch, this brand new, luxury apartment brings you a cozy, refined, functional space for a business trip or a romantic weekend away in the heart of Old City, Philadelphia.",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1608982221/peace-village/wonderlane-i37geFnqA4w-unsplash_udr1g1.jpg",
    host: "5d378db94e84753160e08b59",
    type: ListingType.Apartment,
    address: "250  Saint Clair Street, Dubai, United Arab Emirates",
    country: "United Arab Emirates",
    admin: "Dubai",
    city: "Dubai",
    bookings: [],
    bookingsIndex: {},
    price: 97211,
    numOfGuests: 2,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b3a"),
    title: "30 day minimum, long term rental only",
    description:
      "Reasonable price and an amazing location! Experience the Real French Quarter! Close by all the attractions, full of charm and ready for you! We book up fast so secure your dates now. Years of good reviews and half the price of comparable listings!",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1608982221/peace-village/faizah-othman-AhYvn9hqPPY-unsplash_uoe8ny.jpg",
    host: "5d378db94e84753160e08b56",
    type: ListingType.Apartment,
    address: "4963  James Martin Circle, Dubai, United Arab Emirates",
    country: "United Arab Emirates",
    admin: "Dubai",
    city: "Dubai",
    bookings: [],
    bookingsIndex: {},
    price: 42409,
    numOfGuests: 4,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b3b"),
    title: "Yonah Peaceful House",
    description:
      "Welcome to Yonah Retreat House on a 13.5 acres land with green pastures with horses, a pond which is open for fishing, and amazing view of Yonah Mountain. The house is spacious ideal for singles, couples, retreats, family reunion (with kids), big group (10 max due to the Covid 19) . Many wedding parties (bridals and grooms) have stayed.",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1608982222/peace-village/steve-doig-k3yc_xt-GzY-unsplash_c5lsej.jpg",
    host: "5d378db94e84753160e08b56",
    type: ListingType.House,
    address: "4461  Northwest Boulevard, United Arab Emirates",
    country: "United Arab Emirates",
    admin: "Dubai",
    city: "Dubai",
    bookings: [],
    bookingsIndex: {},
    price: 50543,
    numOfGuests: 4,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b3c"),
    title: "Luxury Log Cabin with Mountain View ",
    description:
      "Log Heaven is located only 5 miles from HELEN, GA on the backside off of Alt 75. This AUTHENTIC log cabin provides the best in CONVENIENCE and LUXURY.",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1608982222/peace-village/gene-giromini-ltuYxBXUcSU-unsplash_mjmxmo.jpg",
    host: "5d378db94e84753160e08b57",
    type: ListingType.House,
    address: "4903  Emeral Dreams Drive, Dubai, United Arab Emirates",
    country: "United Arab Emirates",
    admin: "Dubai",
    city: "Dubai",
    bookings: [],
    bookingsIndex: {},
    price: 40900,
    numOfGuests: 4,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b3d"),
    title: "Safe City Getaway - Less than 5 Min to Everything!",
    description:
      "Everything you will need within walking distance and the MARTA subway train station to connect to all of Atlanta. There are several shops, restaurants, and nightlife nearby. Perfect weekend getaway for couples, families, athletic fans",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1608982222/peace-village/gayatri-malhotra-h7x2YnM1jWM-unsplash_ts2ulo.jpg",
    host: "5d378db94e84753160e08b56",
    type: ListingType.Apartment,
    address: "1935  Buck Drive, Dubai, United Arab Emirates",
    country: "United Arab Emirates",
    admin: "Dubai",
    city: "Dubai",
    bookings: [],
    bookingsIndex: {},
    price: 33109,
    numOfGuests: 3,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b3e"),
    title: "Luxury en suite bedroom condo in Dubai Marina",
    description:
      "A luxury condo residence for those looking to travel in style. Condo includes but not limited to direct access to private parking, 200 sq ft balcony, 2 bathrooms, and incredible views of the marina.",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1608982222/peace-village/steve-rogers-fj0DFNzQvTo-unsplash_aeleda.jpg",
    host: "5d378db94e84753160e08b57",
    type: ListingType.Apartment,
    address: "20 Marina Ave, Dubai, United Arab Emirates",
    country: "United Arab Emirates",
    admin: "Dubai",
    city: "Dubai",
    bookings: [],
    bookingsIndex: {},
    price: 90432,
    numOfGuests: 2,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b3f"),
    title: "Midtown 1 bedrm apt walk to restaurants and more",
    description:
      "This place has a very unique feel of old and new. Nestled in a historic neighborhood, you will feel the spaciousness of a peaceful space.",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1608982222/peace-village/toa-heftiba-ww_18Ti24Zo-unsplash_s3f49c.jpg",
    host: "5d378db94e84753160e08b58",
    type: ListingType.House,
    address: "Ironwood, Branch, Tennessee, United States",
    country: "United States",
    admin: "Memphis",
    city: "Tennessee",
    bookings: [],
    bookingsIndex: {},
    price: 32612,
    numOfGuests: 3,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b40"),
    title: "The House of Blues at Pettigrew Adventures",
    description:
      "Pettigrew Adventures #1 is a fully renovated two bedroom, 1 bathroom private condo with a modern style decor. A stay in my place beats a hotel room any day. Each bedroom boasts a comfy king sized bed and plenty of space for your things.",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1608983219/peace-village/jacques-bopp-Hh18POSx5qk-unsplash_qwvxya.jpg",
    host: "5d378db94e84753160e08b58",
    type: ListingType.House,
    address: "1910  Owagner Lane, Washington",
    country: "United States",
    admin: "Washington",
    city: "Seattle",
    bookings: [],
    bookingsIndex: {},
    price: 12817,
    numOfGuests: 4,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b41"),
    title: "Charming 1 BR Apartment in Downtown Free WiFi",
    description:
      "The Exchange, completed in 1910, once housed the Cotton and Merchant's Exchange where fortunes were won and lost. Today, the revitalized Exchange Building is a mixed-use hotel and residences, first of its kind in Memphis.",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1608983219/peace-village/florian-schmidinger-b_79nOqf95I-unsplash_yi1tjt.jpg",
    host: "5d378db94e84753160e08b56",
    type: ListingType.House,
    address: "612 Cindy Dr, Cookeville United States",
    country: "United States",
    admin: "California",
    city: "Los Angeles",
    bookings: [],
    bookingsIndex: {},
    price: 94576,
    numOfGuests: 3,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b42"),
    title: "Best View in Town! Newly renovated Apt - Free WiFi",
    description:
      "This apartment is located in the Historic Memphis Merchants' Exchange Building in the heart of Downtown Memphis. The apartment was recently renovated and re-designed! The cozy living space includes a full-kitchen, cozy living room, & one-bedroom.",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1608983219/peace-village/rowan-heuvel-bjej8BY1JYQ-unsplash_tmhgjc.jpg",
    host: "5d378db94e84753160e08b59",
    type: ListingType.Apartment,
    address: "100 Meadow Rd, Hyde Park, California",
    country: "United States",
    admin: "California",
    city: "Los Angeles",
    bookings: [],
    bookingsIndex: {},
    price: 69321,
    numOfGuests: 3,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b43"),
    title: "Charming Garage Apartment",
    description:
      "Great reviews in a great neighborhood! Newly renovated garage apartment. Has everything you need for a comfortable stay including fully equipped kitchen. Located in the prime Montrose location with the coffee shop around the corner.",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1608983219/peace-village/simon-lund-O9TBXOmyN2I-unsplash_tfekvt.jpg",
    host: "5d378db94e84753160e08b56",
    type: ListingType.Apartment,
    address: "404 Bobcat Cir, Havelock, Los Angeles, California",
    country: "United States",
    admin: "California",
    city: "Los Angeles",
    bookings: [],
    bookingsIndex: {},
    price: 99320,
    numOfGuests: 3,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b44"),
    title: "Modern Spartan Mansion Guesthouse",
    description:
      "Fully remodeled 1955 Spartan Mansion with a modern interior, expansive deck, and all the conveniences of a high end hotel. In the center of vibrant east Austin. ",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1608983219/peace-village/irina-murza-PJMbzWAz26M-unsplash_udtwt7.jpg",
    host: "5d378db94e84753160e08b58",
    type: ListingType.House,
    address: "2891 Suspiro Via, San Ysidro, Los Angeles, California",
    country: "United States",
    admin: "California",
    city: "Los Angeles",
    bookings: [],
    bookingsIndex: {},
    price: 10537,
    numOfGuests: 3,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b45"),
    title: "Modern Hyde Park Studio - Monthly Discounts",
    description:
      "Our private studio is located in our backyard with parking in front of our house. You can walk to Hyde Park Village, the Triangle or North Loop and it is minutes to downtown and UT.",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1608983220/peace-village/benjamin-rascoe-1nao7-vs7m4-unsplash_ruzopb.jpg",
    host: "5d378db94e84753160e08b59",
    type: ListingType.House,
    address: "200 Copper Rd, Los Angeles, California",
    country: "United States",
    admin: "Austin",
    city: "Texas",
    bookings: [],
    bookingsIndex: {},
    price: 79237,
    numOfGuests: 3,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b46"),
    title: "Take in a Dip in the Heated Pool at a Luxury SoCo Retreat",
    description:
      "Kick back on the plush day bed under the canvas shade at this deluxe, contemporary hideaway in coveted Travis Heights. Take a cooling afternoon dip in the heated pool surrounded by tropical plants, limestone, Brazilian decking, and mature landscaping.",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1608983220/peace-village/phil-hearing-IYfp2Ixe9nM-unsplash_jw840v.jpg",
    host: "5d378db94e84753160e08b59",
    type: ListingType.House,
    address: "301 Hillhaven Dr, Los Angeles, California",
    country: "United States",
    admin: "California",
    city: "Los Angeles",
    bookings: [],
    bookingsIndex: {},
    price: 15632,
    numOfGuests: 3,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b47"),
    title: "Spacious And Comfortabel Room.",
    description:
      "Easy access to the room without disturbing anyone when entering and exiting the house.- A very comfortable bed: Double bed 180 cm x200 cm- Good heather that can be easily adjusted.",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1608983220/peace-village/troy-spoelma-uBEC76XRJwM-unsplash_lekzxl.jpg",
    host: "5d378db94e84753160e08b57",
    type: ListingType.Apartment,
    address: "7811 Shaffer Pl, Littleton, Los Angeles, California",
    country: "United States",
    admin: "California",
    city: "Los Angeles",
    bookings: [],
    bookingsIndex: {},
    price: 12212,
    numOfGuests: 3,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b48"),
    title: "Canal house in center+ bike+ sauna+ parking option",
    description:
      "This canal house is located in the city center at the picturesque Prinsengracht, facing the famous nine little streets, which is a unique area for shopping. Anne Frank House, Van Gogh museum and Vondelpark are a 10-minute walk.",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1608983220/peace-village/david-veksler-VW5YwCYbPyk-unsplash_wle4zk.jpg",
    host: "5d378db94e84753160e08b57",
    type: ListingType.Apartment,
    address: "4963  Polk Street, London, United Kingdom",
    country: "United Kingdom",
    admin: "England",
    city: "London",
    bookings: [],
    bookingsIndex: {},
    price: 22066,
    numOfGuests: 3,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b49"),
    title: "Nice studio a short walk from the Bastille",
    description:
      "Nice and quiet studio of 33 sq. mt. well lit by a glass wall, with folding bed, kitchenette, bathroom and separate toilet. Located just a short walk from the Bastille, the apartment is located in a historic building, Leon Mager, which was renovated in the 90s.",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1608983222/peace-village/max-kukurudziak--xuG3Gi8srA-unsplash_mcnw3v.jpg",
    host: "5d378db94e84753160e08b59",
    type: ListingType.Apartment,
    address: "4983  Polk Street, London, United Kingdom",
    country: "United Kingdom",
    admin: "England",
    city: "London",
    bookings: [],
    bookingsIndex: {},
    price: 21123,
    numOfGuests: 3,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b4a"),
    title: "Charmant duplex avec terrasse aménagée",
    description:
      "Très beau duplex de 60 mètres carrés situé dans le 17ème arrondissement de Paris au coeur de la rue de Lévis à deux minutes du métro Villiers (lignes 2 et 3). Il est localisé au rez-de-chaussée.",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1608984680/peace-village/satyam-hcr-McyDzKpNqFI-unsplash_lkgd2g.jpg",
    host: "5d378db94e84753160e08b56",
    type: ListingType.House,
    address: "1648  Jarvisville Road, London, United Kingdom",
    country: "United Kingdom",
    admin: "England",
    city: "London",
    bookings: [],
    bookingsIndex: {},
    price: 76128,
    numOfGuests: 3,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b4b"),
    title: "Charming Home Away From Home - Lackland AFB!",
    description:
      "The house is in an extremely safe and new neighborhood surrounded by family-friendly neighbors. Military-friendly as well, as Lackland AFB is only 2 miles away! You will also be less than 1 mile away from Walmart and Subway.",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1608984680/peace-village/satyam-hcr-MUExQImPO0I-unsplash_znt2nh.jpg",
    host: "5d378db94e84753160e08b55",
    type: ListingType.House,
    address: "4189  Bridge Avenue, London, United Kingdom",
    country: "United States",
    admin: "England",
    city: "London",
    bookings: [],
    bookingsIndex: {},
    price: 89022,
    numOfGuests: 4,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b4c"),
    title: "Spacious Master Bedroom Near Downtown!!",
    description:
      "Newly bought house with a brand new room set up! Right by the downtown area, surrounded by locally owned restaurants. Mini Fridge now in the room!",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1608984680/peace-village/marcelo-rivas-4b4Fu9-SqaU-unsplash_n6i0wx.jpg",
    host: "5d378db94e84753160e08b55",
    type: ListingType.House,
    address: "4637  D Street, London, United Kingdom",
    country: "United Kingdom",
    admin: "England",
    city: "London",
    bookings: [],
    bookingsIndex: {},
    price: 10998,
    numOfGuests: 3,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b4d"),
    title: "North Oak Lawn-Highland Park Adjacent-Modern",
    description:
      "Private town home, central Dallas location, Highland Park/Oak Lawn area. Walk to Turtle Creek, parks-walking trails and church. Next door to Al Biernat's restaurant (A Dallas ICON). Steps away from The Shops of Highland Park and Chocolate!",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1609321925/peace-village/e49590aa-b5b1-4aa6-a817-8e345f2d7b00_fmbdqh.webp",
    host: "5d378db94e84753160e08b57",
    type: ListingType.House,
    address: "1350  Wiseman Street, London, United Kingdom",
    country: "United Kingdom",
    admin: "England",
    city: "London",
    bookings: [],
    bookingsIndex: {},
    price: 18587,
    numOfGuests: 4,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b4e"),
    title: "Cute bedroom in best part of Arlington",
    description:
      "Each bedroom has private bathroom. Walk Score 75 (walkable to cafes, dining, shopping). Private rooftop with downtown Dallas views. Fully equipped + stocked kitchen. Onsite, garage parking for 2 vehicles. Onsite washer + dryer",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1609321987/peace-village/b36c61e4-c7ab-4570-b5a9-edffb54d1391_gy1av4.webp",
    host: "5d378db94e84753160e08b59",
    type: ListingType.Apartment,
    address: "1051  Creekside Lane, London, United Kingdom",
    country: "United Kingdom",
    admin: "England",
    city: "London",
    bookings: [],
    bookingsIndex: {},
    price: 33349,
    numOfGuests: 3,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b4f"),
    title: "Spacious Room & Full Bathroom, Fridge & Microwave",
    description:
      "This is a quiet and friendly neighborhood. It is surrounded with art of state malls (Town East Mall which is just 15 minutes away and Road Ridge Shopping Center in Rockwall which is 20 minutes away). The places to have dinner are nearby.",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1609322104/peace-village/0990f82b-4ad9-4ddc-bcef-dc5e7c58cf84_qpfstc.webp",
    host: "5d378db94e84753160e08b59",
    type: ListingType.Apartment,
    address: "655  Stonecoal Road, London, United Kingdom",
    country: "United Kingdom",
    admin: "England",
    city: "London",
    bookings: [],
    bookingsIndex: {},
    price: 20823,
    numOfGuests: 4,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b50"),
    title: "Cute Nashville apartment!",
    description:
      "You cannot beat this location! Brand new renovated apartment. Great view overlooking beautiful Sevier Park. A quick walk through the park gets you to all the shops and restaurants on 12th!",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1609322160/peace-village/164c8200-d8f7-458a-9935-2af1a372c852_rhoi0y.webp",
    host: "5d378db94e84753160e08b56",
    type: ListingType.Apartment,
    address: "1552  Matthews Street, San Fransisco, California",
    country: "United States",
    admin: "California",
    city: "San Francisco",
    bookings: [],
    bookingsIndex: {},
    price: 22289,
    numOfGuests: 3,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b51"),
    title: "Stunning 1 bedroom right off of Lower Broadway",
    description:
      "30 NIGHT STAY MINIMUM!! This is a stunning fully furnished 1 bed/ 1 bath unit is just steps to Broadway Street, downtown, amazing restaurants and nightlife, and everything else this great area has to offer.",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1609322213/peace-village/85cd8382-9698-483c-9e1c-7eb76e318e03_xh2bdx.webp",
    host: "5d378db94e84753160e08b56",
    type: ListingType.Apartment,
    address: "3433  Rubaiyat Road, San Fransisco, California",
    country: "United States",
    admin: "California",
    city: "San Francisco",
    bookings: [],
    bookingsIndex: {},
    price: 32331,
    numOfGuests: 4,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b52"),
    title: "Music Row Getaway 4",
    description:
      "Fully furnished, private apartment located on the iconic Music Row within walking distance to the Gulch, Midtown, and Demonbreun. Broadway is exactly 1 mile away!! The apartment has fresh paint, laminate flooring, Full size stove and refrigerator.",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1609322268/peace-village/4b2acb8a-7af5-4dc1-bff4-caba1d0e61bb_d5ivrj.webp",
    host: "5d378db94e84753160e08b59",
    type: ListingType.Apartment,
    address: "3646  Ethels Lane, San Fransisco, California",
    country: "United States",
    admin: "California",
    city: "San Francisco",
    bookings: [],
    bookingsIndex: {},
    price: 44065,
    numOfGuests: 2,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b53"),
    title: "Wonderful Space with Free Street Parking",
    description:
      "Perfect room with queen size bed and shared bath. This room has all you need to relax after a day of visiting family or all the wonders of Chicago. You are only a few blocks to one of Chicago’s best and cleanest train lines.",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1609322321/peace-village/799403ef-52e7-4ee6-b8e6-12f6f8d143f7_mxvsfq.webp",
    host: "5d378db94e84753160e08b56",
    type: ListingType.House,
    address: "1017  Carolina Avenue, Cancún, Mexico",
    country: "Mexico",
    admin: "Quintana Roo",
    city: "Cancún",
    bookings: [],
    bookingsIndex: {},
    price: 99091,
    numOfGuests: 3,
  },
  {
    _id: new ObjectId("5d378db94e84753160e08b54"),
    title: "Trendy Space Near Downtown Atlanta",
    description:
      "Trendy & trending near downtown Atlanta. This beautiful skyline is calling your name. Upgrade your stay while visiting our contemporary loft style apartment in a friendly community, that's designed to appeal to those looking for a mix of stunning views and modern touches.",
    image:
      "https://res.cloudinary.com/munirmahmud/image/upload/v1609322364/peace-village/f37aab2d-2d96-4419-bbd3-9bb6b5f7af08_g0e5va.webp",
    host: "5d378db94e84753160e08b56",
    type: ListingType.Apartment,
    address: "4639  Richison Drive, Cancún, Mexico",
    country: "Mexico",
    admin: "Quintana Roo",
    city: "Cancún",
    bookings: [],
    bookingsIndex: {},
    price: 41180,
    numOfGuests: 6,
  },
];

const users: User[] = [
  {
    _id: "5d378db94e84753160e08b55",
    token: "token_************",
    name: "Raymond Schmid.",
    avatar: "https://randomuser.me/api/portraits/men/46.jpg",
    contact: "raymondschmid@peacevillage.com",
    walletId: "acct_************",
    income: 65432,
    bookings: [],
    listings: [
      new ObjectId("5d378db94e84753160e08b31"),
      new ObjectId("5d378db94e84753160e08b4b"),
      new ObjectId("5d378db94e84753160e08b4c"),
    ],
  },
  {
    _id: "5d378db94e84753160e08b56",
    token: "token_************",
    name: "Alice T Bailey.",
    avatar: "https://randomuser.me/api/portraits/women/89.jpg",
    contact: "alicebailey@peacevillage.com",
    walletId: "acct_************",
    income: 98743,
    bookings: [],
    listings: [
      new ObjectId("5d378db94e84753160e08b37"),
      new ObjectId("5d378db94e84753160e08b38"),
      new ObjectId("5d378db94e84753160e08b3a"),
      new ObjectId("5d378db94e84753160e08b3b"),
      new ObjectId("5d378db94e84753160e08b3d"),
      new ObjectId("5d378db94e84753160e08b41"),
      new ObjectId("5d378db94e84753160e08b43"),
      new ObjectId("5d378db94e84753160e08b4a"),
      new ObjectId("5d378db94e84753160e08b50"),
      new ObjectId("5d378db94e84753160e08b51"),
      new ObjectId("5d378db94e84753160e08b53"),
      new ObjectId("5d378db94e84753160e08b54"),
    ],
  },
  {
    _id: "5d378db94e84753160e08b57",
    token: "token_************",
    name: "Christopher N",
    avatar: "https://randomuser.me/api/portraits/men/72.jpg",
    contact: "christopher@peacevillage.com",
    walletId: "acct_************",
    income: 59874,
    bookings: [],
    listings: [
      new ObjectId("5d378db94e84753160e08b30"),
      new ObjectId("5d378db94e84753160e08b32"),
      new ObjectId("5d378db94e84753160e08b34"),
      new ObjectId("5d378db94e84753160e08b35"),
      new ObjectId("5d378db94e84753160e08b36"),
      new ObjectId("5d378db94e84753160e08b3c"),
      new ObjectId("5d378db94e84753160e08b3e"),
      new ObjectId("5d378db94e84753160e08b47"),
      new ObjectId("5d378db94e84753160e08b48"),
      new ObjectId("5d378db94e84753160e08b4d"),
    ],
  },
  {
    _id: "5d378db94e84753160e08b58",
    token: "token_************",
    name: "Kelly R Geisler",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    contact: "kellygeisler@peacevillage.com",
    walletId: "acct_************",
    income: 54309,
    bookings: [],
    listings: [
      new ObjectId("5d378db94e84753160e08b3f"),
      new ObjectId("5d378db94e84753160e08b40"),
      new ObjectId("5d378db94e84753160e08b44"),
    ],
  },
  {
    _id: "5d378db94e84753160e08b59",
    token: "token_************",
    name: "Jason D Powell.",
    avatar: "https://randomuser.me/api/portraits/men/40.jpg",
    contact: "jason@peacevillage.com",
    walletId: "acct_************",
    income: 87634,
    bookings: [],
    listings: [
      new ObjectId("5d378db94e84753160e08b33"),
      new ObjectId("5d378db94e84753160e08b39"),
      new ObjectId("5d378db94e84753160e08b42"),
      new ObjectId("5d378db94e84753160e08b45"),
      new ObjectId("5d378db94e84753160e08b46"),
      new ObjectId("5d378db94e84753160e08b49"),
      new ObjectId("5d378db94e84753160e08b4e"),
      new ObjectId("5d378db94e84753160e08b4f"),
      new ObjectId("5d378db94e84753160e08b52"),
    ],
  },
];

const seed = async () => {
  try {
    console.log("[seed] : running...");

    const db = await connectDatabase();

    for (const listing of listings) {
      await db.listings.insertOne(listing);
    }

    for (const user of users) {
      await db.users.insertOne(user);
    }

    console.log("[seed] : success");
  } catch {
    throw new Error("failed to seed database");
  }
};

seed();
